/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\lib\astryxTheme.ts
 * Command: astryx theme build src\lib\astryxTheme.ts
 * Generated: 2026-07-29T13:14:25.866Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const eazypostTheme: DefinedTheme;
