/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\lib\astryxTheme.ts
 * Command: astryx theme build src\lib\astryxTheme.ts
 * Generated: 2026-07-24T22:32:39.481Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const eazypostTheme: DefinedTheme;
