export enum SocialPlatform {
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  TWITTER = 'TWITTER',
  LINKEDIN = 'LINKEDIN',
  TIKTOK = 'TIKTOK',
  YOUTUBE = 'YOUTUBE',
  PINTEREST = 'PINTEREST',
  THREADS = 'THREADS',
  WHATSAPP = 'WHATSAPP',
}
